### ISSUE TITLE
Build it in R Markdooooooooown with the blogdown package

### ISSUE THREAD

**Issue by alexpghayes** [ricedatasci/website#1]

**Comment by gvacaliuc** [comment]
maybe... deciding between various static site generators now. ;)

**Comment by gvacaliuc** [comment]
Looks like [blogdown](https://bookdown.org/yihui/blogdown/hugo.html) just executes the Rmd into md and uses hugo to compile the site, which is the static site generator I'm planning on using.  

As long as you can do (.Rmd -> .md, .ipynb -> .md) it's all the same.
